async def get_collection_list() -> list:
    qdrant_collections = [
        "mood_and_emotions",
        "anxiety_and_stress",
        "depression_and_burnout",
        "self_reflection_and_thoughts",
        "dreams_and_subconscious",
        "fitness_and_exercise",
        "diet_and_nutrition",
        "illness_and_symptoms",
        "sleep_and_fatigue",
        "medical_appointments_or_health_logs",
        "love_life_or_romantic",
        "family_and_home",
        "friends_and_social",
        "breakups_and_conflicts",
        "loneliness_and_companionship",
        "workload_and_projects",
        "job_stress",
        "team_and_communication",
        "career_planning",
        "interviews_and_opportunities",
        "personal_goals",
        "daily_routines",
        "habit_tracking",
        "motivation_and_productivity",
        "time_management",
        "books_and_knowledge",
        "courses_and_skills",
        "self_improvement_or_mindset",
        "language_learning",
        "creativity_and_ideas",
        "tech_and_gadgets",
        "social_media_and_online_activity",
        "movies_and_tv_shows",
        "music_and_podcasts",
        "gaming",
        "daily_logs_and_check_ins",
        "shopping_and_spending",
        "travel_and_places",
        "random_thoughts_or_miscellaneous",
        "news_and_world_events"
    ]

    return qdrant_collections
